# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - test5

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ststest.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e5822c18e7b24e6790e603ba34d66506 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cb22cba74ac7442e833d34b93cefd236 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        tags: ststest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e5822c18e7b24e6790e603ba34d66506 }}/java:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'test5'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9c2bf51eb398496c979dfca9d7f27454 }}
        images: 'ststest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e5822c18e7b24e6790e603ba34d66506 }}/java:${{ github.sha }}'
