# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - javatest1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package

    - name: Verify JAR file
      run: ls -l target

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ststest.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_05b3aeda69634b85b3c66e8ecd2c6a89 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_878d7cfe3b584ac298d770e8f80f1083 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ststest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_05b3aeda69634b85b3c66e8ecd2c6a89 }}/java:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'javatest1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4623eae71fb145e38114b360286105e8 }}
        images: 'ststest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_05b3aeda69634b85b3c66e8ecd2c6a89 }}/java:${{ github.sha }}'
